# Generated by Django 5.1.3 on 2024-11-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(blank=True, null=True, related_name='estudiantes', to='academia.curso'),
        ),
    ]
