# Generated by Django 5.1.3 on 2024-11-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_alter_estudiante_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='academia.curso'),
        ),
    ]
