# Generated by Django 5.1.3 on 2024-11-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_curso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
